spring.application.name=TestJava2BBDD API
server.port=${PORT:8080}
server.servlet.context-path=/
spring.web.resources.static-locations=classpath:/static/

# Logging
logging.level.root=INFO
logging.level.com.testjava2bbdd=DEBUG

# Spring Web
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true
